log_level = "INFO"
logs_folder = "logs"
stream_urls = []
streamlink_cli = 'streamlink --force --logfile "logs\{source}_{timestamp}.log" --output "streams\{author}_{time:%Y%m%d-%H%M%S}.mp4" --twitch-disable-ads --default-stream "1080p, 720p, best" --url {url}'
